# Generated by Django 3.2.16 on 2025-03-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250320_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_up',
        ),
    ]
